# Generated by Django 6.0.7 on 2026-07-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0002_aluno_disciplina_turma_nota_aluno_turma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="turma",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="disciplina",
        ),
        migrations.DeleteModel(
            name="Turma",
        ),
        migrations.DeleteModel(
            name="Aluno",
        ),
        migrations.DeleteModel(
            name="Disciplina",
        ),
        migrations.DeleteModel(
            name="Nota",
        ),
    ]
