# Generated by Django 6.0.3 on 2026-03-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("local", models.CharField(max_length=100)),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="festivais.banda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="banda",
            name="genero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="festivais.genero"
            ),
        ),
    ]
