# Generated by Django 6.0.7 on 2026-07-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festivais", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dia",
            options={"ordering": ["data"]},
        ),
        migrations.RemoveField(
            model_name="dia",
            name="numero",
        ),
    ]
