# Generated by Django 6.0.3 on 2026-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("nome", models.CharField(max_length=100)),
                ("turma", models.CharField(max_length=10)),
                ("idade", models.IntegerField()),
            ],
        ),
    ]
