# Generated by Django 6.0.7 on 2026-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("grau", models.CharField(max_length=50)),
                ("duracao_anos", models.IntegerField()),
                (
                    "instituicao",
                    models.CharField(default="Universidade Lusófona", max_length=150),
                ),
                ("ects_totais", models.IntegerField()),
            ],
        ),
    ]
