# Generated by Django 6.0.7 on 2026-07-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=300)),
                ("orientadores", models.CharField(max_length=300)),
                ("ano", models.IntegerField()),
                ("link_pdf", models.URLField(blank=True)),
                ("imagem", models.URLField(blank=True)),
                ("sumario", models.TextField(blank=True)),
                ("palavras_chave", models.CharField(blank=True, max_length=300)),
                ("areas", models.CharField(blank=True, max_length=300)),
                ("tecnologias", models.CharField(blank=True, max_length=300)),
                ("rating", models.IntegerField(default=0)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
