# Generated by Django 6.0.7 on 2026-07-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("grau", models.CharField(blank=True, max_length=50)),
                ("cienciavitae", models.CharField(blank=True, max_length=50)),
                ("orcid", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="apresentacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="coordenador",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="coordenador_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="saidas_profissionais",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="licenciaturas", to="portfolio.docente"
            ),
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nome", models.CharField(max_length=150)),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=30)),
                ("ects", models.IntegerField()),
                ("tipo", models.CharField(blank=True, max_length=30)),
                ("natureza", models.CharField(blank=True, max_length=30)),
                ("objetivos", models.TextField(blank=True)),
                ("programa", models.TextField(blank=True)),
                ("bibliografia", models.TextField(blank=True)),
                ("avaliacao", models.TextField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
