# Generated by Django 6.0.7 on 2026-07-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_docente_licenciatura_apresentacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docente",
            name="cienciavitae",
        ),
        migrations.RemoveField(
            model_name="docente",
            name="grau",
        ),
        migrations.RemoveField(
            model_name="docente",
            name="orcid",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="apresentacao",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="coordenador",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="coordenador_email",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="saidas_profissionais",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="url",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="avaliacao",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="bibliografia",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="natureza",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="objetivos",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="programa",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="tipo",
        ),
    ]
