# Generated by Django 6.0.7 on 2026-07-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_docente_cienciavitae_remove_docente_grau_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("instituicao", models.CharField(max_length=150)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("certificado_link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("logo", models.URLField(blank=True)),
                ("site_oficial", models.URLField(blank=True)),
                ("nivel_interesse", models.IntegerField(help_text="1 a 5")),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("imagem", models.URLField(blank=True)),
                ("video_demo", models.URLField(blank=True)),
                ("link_github", models.URLField(blank=True)),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=50)),
                ("nivel", models.IntegerField(help_text="1 a 5")),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="competencias", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
    ]
