# Generated by Django 6.0.7 on 2026-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_formacao_tecnologia_projeto_competencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="unidades_curriculares", to="portfolio.docente"
            ),
        ),
    ]
