# Generated by Django 6.0.7 on 2026-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_tipotecnologia_tecnologia_opiniao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        help_text="Ex: Projeto, Tecnologia, MakingOf", max_length=100
                    ),
                ),
                ("decisao", models.TextField(help_text="Decisão de modelação tomada")),
                ("justificacao", models.TextField()),
                ("erro_encontrado", models.TextField(blank=True)),
                ("correcao", models.TextField(blank=True)),
                (
                    "uso_ia",
                    models.TextField(
                        blank=True, help_text="Como a IA contribuiu (ou não)"
                    ),
                ),
                (
                    "foto",
                    models.URLField(
                        blank=True,
                        help_text="Foto do caderno/DER/esquema, ex via Cloudinary",
                    ),
                ),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
