# Generated by Django 6.0.7 on 2026-07-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
