# Generated by Django 6.0.7 on 2026-07-18 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_artigo_dislikes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="autor",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontuacao", models.IntegerField(help_text="1 a 5")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "artigo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="artigos.artigo",
                    ),
                ),
            ],
        ),
    ]
